[package]
name = "crypto-demo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
rust-crypto = "0.2.36"
rustc-serialize = "0.3.24"
